
debug=false
spring.jpa.show-sql=false
  # 日志目录
logging.file.path=/release_log
  
  # Spring Boot 如果发现 Tomcat 连接池不可用，则尝试选择 HikariCP 作为默认连接池
spring.datasource.hikari.maximum-pool-size=200
  
  # 线上数据库
  # 内网
spring.datasource.url=jdbc:mysql://rm-wz90fx7092498yl0y90150.mysql.rds.aliyuncs.com:3306/wander
  # 内网，线上redis
spring.redis.host=r-wz9cxn6gjl6q8deb8m.redis.rds.aliyuncs.com
  
  # es索引名前缀
es.index.prefix =product_