
spring.jpa.show-sql=false
  # 日志目录
logging.file.path=/test_log
  
  # 测试数据库
  # 内网
spring.datasource.url=jdbc:mysql://rm-wz90fx7092498yl0y90150.mysql.rds.aliyuncs.com:3306/test_wander
  # 内网
spring.redis.host=r-wz9kptcopoihe5n47n.redis.rds.aliyuncs.com
  
  # es索引名前缀
es.index.prefix =test_
